# NumPy 

•	The name is an acronym for "Numeric Python" or "Numerical Python"

•	NumPy (or Numpy) is a Linear Algebra Library for Python

•   The reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely     on NumPy as one of their main building blocks.


## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    pip install numpy



## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

# Numpy Arrays

•	Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.

• Array is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

• NumPy’s array class is called ndarray. It is also known by the alias array.

• NumPy supports multidimensional arrays over which you can easily apply mathematical operations.

• It executes computations and mathematical calculations in an element-wise manner.

## Creating NumPy Arrays

### From a Python List , Tuples 

We can create an array by directly converting a list or list of lists:

In [ ]:
li = [5,8,9,4,7,9]
tu = (5,8,9,4,7,9)

In [ ]:
arr = np.array(li)
arr

array([5, 8, 9, 4, 7, 9])

In [ ]:
my_matrix = [[25,65,8],[6,8,1],[6,8,4]]
my_matrix

[[25, 65, 8], [6, 8, 1], [6, 8, 4]]

In [ ]:
arr = np.array(my_matrix)
arr

array([[25, 65,  8],
       [ 6,  8,  1],
       [ 6,  8,  4]])

### Checking the dimesnions of a array

In [ ]:
arr.ndim

2

### Checking the size of a array

In [ ]:
arr.size

9

### Checking the data type of a array

In [ ]:
arr.dtype

dtype('int32')

### Checking the shape of a array
Shape is an attribute that arrays have (not a method):

In [ ]:
arr.shape

(3, 3)

## Built-in Methods

ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

numpy.arange( start(default = 0) , stop , step(default = 1) )

If `step` is specified as a position argument, `start` must also be given.

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,30,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5])

### linspace
Return evenly spaced numbers over a specified interval.

#### Syntax 
np.linspace  (start , stop , num=50)


In [ ]:
np.linspace(0,100,45)

array([  0.        ,   2.27272727,   4.54545455,   6.81818182,
         9.09090909,  11.36363636,  13.63636364,  15.90909091,
        18.18181818,  20.45454545,  22.72727273,  25.        ,
        27.27272727,  29.54545455,  31.81818182,  34.09090909,
        36.36363636,  38.63636364,  40.90909091,  43.18181818,
        45.45454545,  47.72727273,  50.        ,  52.27272727,
        54.54545455,  56.81818182,  59.09090909,  61.36363636,
        63.63636364,  65.90909091,  68.18181818,  70.45454545,
        72.72727273,  75.        ,  77.27272727,  79.54545455,
        81.81818182,  84.09090909,  86.36363636,  88.63636364,
        90.90909091,  93.18181818,  95.45454545,  97.72727273,
       100.        ])

## Random 

It is used to create random number arrays:

### rand
Create an array of the given shape, with random samples from a uniform distribution over ``[0, 1)``.(Normal Distribution)

A normal distribution is a distribution where the values are more likely to occur near the mean value. 

Here `[` means 0 is included and `)` means 1 is excluded

In [ ]:
# gives 10 random numbers between 0 to 1
np.random.rand(10)

array([0.45492758, 0.7656117 , 0.35706077, 0.69816002, 0.29341349,
       0.67805452, 0.8887177 , 0.35761374, 0.16933639, 0.86741072])

In [ ]:
# gives 18 (6*2) random numbers between 0 to 1 in form of 2-D array as per the shape specified
np.random.rand(6,2)

array([[0.57670347, 0.41824909],
       [0.78677973, 0.49989303],
       [0.49529628, 0.36269595],
       [0.79729657, 0.97427272],
       [0.17562944, 0.69075234],
       [0.74218498, 0.34306121]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,40)

17

In [ ]:
np.random.randint(1,40,10)

array([11, 22, 15, 25, 23, 22,  7, 16, 17,  5])

In [ ]:
np.random.randint(1,40,size=(5, 2))

array([[11, 39],
       [13, 33],
       [ 4, 35],
       [12, 18],
       [ 5, 34]])

## Reshape
Returns an array containing the same data with a new shape.

### Transpose the 2-D matrix


In [ ]:
arr = np.arange(10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
arr.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [ ]:
arr.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

### Flatten
We can use flatten method to get a copy of array collapsed into one dimension.

In [ ]:
arr = np.random.rand(3,4) 
arr1 = arr.flatten()
arr1

array([0.91010373, 0.76464656, 0.80246875, 0.87314306, 0.2147927 ,
       0.34564465, 0.27349132, 0.73742138, 0.80426106, 0.95861505,
       0.34396812, 0.30686703])

In [ ]:
arr1.shape

(12,)

In [ ]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr.reshape(6,5)     # can also be written as  = arr = np.arange(30).reshape(6,5)
# 6 * 5 = 30

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([47, 22, 25, 29, 22, 32, 19, 10, 24,  5])

In [ ]:
# gives the maximum value
ranarr.max()

47

In [ ]:
# gives the maximum value index
ranarr.argmax()

0

In [ ]:
# gives the maximum value
ranarr.min()

5

In [ ]:
# gives the maximum value index
ranarr.argmin()

4

# Indexing and Selection


In [ ]:
#Creating sample array
arr = np.arange(0,11)

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Updating Array By Index

Numpy arrays differ from list because of their ability to change multiple values with index.

In [ ]:
# updating array by index
arr[6] = 1
arr

array([ 0,  1,  2,  3,  4,  5,  1,  7,  8,  9, 10])

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   1,   7,   8,   9,  10])

In [ ]:
# defining array ones again

arr = np.arange(0,15)

#Important notes on Slices
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=56

slice_of_arr

array([56, 56, 56, 56, 56, 56])

Now note the changes also occur in our original array!

In [ ]:
arr

array([56, 56, 56, 56, 56, 56,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy

array([[25, 65,  8],
       [ 6,  8,  1],
       [ 6,  8,  4]])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**(Recommended). 

In [ ]:
arr_2d = np.array([[78,97,24],[25,1,23],[9,4,2]])

#Show
arr_2d

array([[78, 97, 24],
       [25,  1, 23],
       [ 9,  4,  2]])

In [ ]:
#Indexing row
arr_2d[1]


array([25,  1, 23])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]   , index are passed for row and column

# Getting individual element value
arr_2d[1][0]

25

In [ ]:
# arr_2d[row,col] method
arr_2d[1,0]

25

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[97, 24],
       [ 1, 23]])

In [ ]:
#Shape bottom row  - arr_2d[row][col]
arr_2d[2]

array([9, 4, 2])

In [ ]:
#Shape bottom row  -  arr_2d[row,col] method
arr_2d[2,:]

array([9, 4, 2])

## comparison operators.

In [ ]:
arr = np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
#  returns elements where the calue is True.
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
#  Directly passing the assignment
#  returns elements where the value is True.
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Broadcasting

1. NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method, NumPy automatically broadcasts the smaller array over the larger array. 

2. However, broadcasting does have its own limitations. It is subject to certain constraints as listed here:
    1. When NumPy operates on two arrays, it compares their shapes element-wise. It finds these shapes compatible only if:
                     - Their dimensions are the same, or
                     - One of them has a dimension of size 1
    2. If these conditions are not met, a "ValueError” is thrown, indicating that the arrays have incompatible shapes!
    
3. Broadcasting is possible if the following rules are satisfied 
    1. Array with smaller ndim than the other is prepended with '1' in its shape.
    2. Size in each dimension of the output shape is maximum of the input sizes in that dimension.

In [ ]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([1,2,3]) 

a + b

In [ ]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([1,2]) 

a + b

ValueError: operands could not be broadcast together with shapes (4,3) (2,) 

In [ ]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([3]) 

a + b

array([[ 3,  3,  3],
       [13, 13, 13],
       [23, 23, 23],
       [33, 33, 33]])

## Adding of Diagonals

In [ ]:
a = np.array([[1,1],[1,1]])

In [ ]:
np.trace(a)

2

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
#Taking Square Roots
arr = np.arange(0,11)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
#Calcualting product
np.prod(arr)

0

In [ ]:
#Calcualting mean
np.mean(arr)

5.0

In [ ]:
#Calcualting Standard Deviation
np.std(arr)

3.1622776601683795

In [ ]:
#Calcualting Square
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [ ]:
np.max(arr) #same as arr.max()

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
# Array element from first array (arr1) is raised to the power of element from second element (arr2)(all happens element-wise).
# Both arr1 and arr2 must have same shape and each element in arr1 must be raised to corresponding +ve value from arr2.

arr1 = [2, 2, 2, 2, 2] 
arr2 = [2, 3, 4, 5, 6] 
np.power(arr1, arr2) 

array([ 4,  8, 16, 32, 64], dtype=int32)

## More Methods
[ONLINE LINK](https://www.geeksforgeeks.org/python-numpy/)

# NUMPY SESSION ENDS